// temporary use import because vite installed "type": "module" in package.json
// const mongoose = require("mongoose");
import mongoose from "mongoose";

// ID of User (autogenerated)
// - Login Details (Email and password)*
// - Profile Photo (selection)
// - Age, Gender, Phone Number
// - Default Shipping Address
// - Transaction History & Status

// note capitalisation, it is an object wrapper type
const userSchema = new mongoose.Schema({
  username: {
    type: String,
    unique: true, //TODO, workout unique validator errors
    required: [true, "Username is required"],
  },
  email: {
    type: String,
    unique: true, //TODO, workout unique validator errors
    required: [true, "Email is required"],
    match: [
      /^[-.\w]+@[-.\w]+\.[-.\w]{2,}$/,
      `Email needs to be in correct format`,
    ],
  },
  password: { type: String, required: true },
  firstName: String,
  lastName: String,
  age: { type: Number, min: 0 },
  gender: {
    type: String,
    enum: {
      values: ["M", "F"],
      message: 'Gender must be either "M" or "F"',
    },
  },
  phoneNumber: {
    type: String, //cause can have leading zeros
    match: [/^\d{7,12}$/, `Expected 7-12 digit phone number`],
  },
  orders: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Order", //TODO: To define in Order.js
    },
  ],
});

// Compile the schema into a model:
const User = mongoose.model("User", userSchema);

// Export the model:
// module.exports = User;
export { User };
