const mongoose = require("mongoose");

// ID of User (autogenerated)
// - Login Details (Email and password)*
// - Profile Photo (selection)
// - Age, Gender, Phone Number
// - Default Shipping Address
// - Transaction History & Status

// note capitalisation, it is an object wrapper type
const userSchema = new mongoose.Schema(
  {
    username: {
      type: String,
      unique: true, //TODO, workout unique validator errors
      required: [true, "Username is required"],
      lowercase: true,
      trim: true,
      match: [
        /^[a-z0-9_-]+$/,
        "Username can only contain lowercase letters, numbers, hyphens, and underscores",
      ],
    },
    email: {
      type: String,
      unique: true, //TODO, workout unique validator errors
      required: [true, "Email is required"],
      trim: true,
      match: [
        /^[-.\w]+@[-.\w]+\.[-.\w]{2,}$/,
        `Email needs to be in correct format`,
      ],
    },
    password: {
      type: String,
      required: [true, "Password is required"],
    },
    firstName: {
      type: String,
      trim: true,
      minLength: [2, "Expecting min. 2 characters"],
    },
    lastName: {
      type: String,
      trim: true,
      minLength: [2, "Expecting min. 2 characters"],
    },
    gender: {
      type: String,
      trim: true,
      enum: {
        values: ["M", "F", "X"],
        message: 'Gender must be either "M" or "F" or "X"',
      },
    },
    birthday: {
      type: Date,
      min: [
        new Date(Date.now() - 100 * 365 * 24 * 60 * 60 * 1000),
        "Birthday is unexpectedly too old",
      ], // but this is talking about 100 years before when schema is defined
      max: [Date.now, "Birthday can't be in the future"],
    },
    phoneNumber: {
      type: String, //cause can have leading zeros
      trim: true,
      match: [
        /^\+?[1-9](?:\s?\d){6,14}$/,
        "Expected valid international phone number",
      ],
    },
    profilePhoto: {
      type: String,
      default: "https://www.gravatar.com/avatar/?d=mp",
    },
    defaultShippingAddress: { type: String, trim: true },
  },
  { timestamps: true }
);

// Remove password
userSchema.set("toJSON", {
  transform: (document, returnedObject) => {
    delete returnedObject.password;
  },
});

const User = mongoose.model("User", userSchema);

module.exports = User;
